version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - method: pip
      path: libs/langchain-matrixone
      extra-dependencies:
        - docs
sphinx:
  configuration: docs/conf.py
